name: flutter_firebase_auth_blueprint
description: Firebase Auth blueprint.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_bloc: ^3.2.0
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: 1.2.1

flutter:
  uses-material-design: true
